version: 0.0
os: linux

files:
  - source: target/aws-app.jar
    destination: /home/ec2-user/deployments/

hooks:
  
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300